features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://1f945270af7c918ab1caef374b0732df.png'
favicon:
  use_default: true
